package dev.gambleclient.module.modules.ai;

public enum MiningState {
    IDLE,
    CENTERING,
    SCANNING_PRIMARY,
    MINING_PRIMARY,
    HAZARD_DETECTED,
    CALCULATING_DETOUR,
    FOLLOWING_DETOUR,
    CHANGING_DIRECTION,
    ROTATING,
    RTP_INITIATED,
    RTP_WAITING,
    RTP_COOLDOWN,
    RTP_SCANNING_GROUND,
    SEARCHING_SAFE_MINEDOWN,
    MOVING_TO_MINEDOWN,
    MINING_DOWN,
    STOPPED
}